language: objective-c
before_script:
    - brew update
    - brew upgrade xctool
script:
    - xctool -project SBJson.xcodeproj -sdk iphonesimulator -scheme sbjson-ios test
    - xctool -project SBJson.xcodeproj -sdk macosx -scheme SBJson test
