version: 2.1

orbs:
    macos: circleci/macos@2

executors:
    default:
        macos:
            # https://circleci.com/docs/using-macos/#supported-xcode-versions
            xcode: 15.4.0

workflows:
    build-and-test:
        jobs:
            - test-ios

jobs:
    test-ios:
        executor: default
        steps:
            - macos/preboot-simulator:
                    version: "15.0"
                    platform: "iOS"
                    device: "iPhone 15 Pro"
            - checkout
            - run:
                name: Run tests
                command: >
                    xcodebuild test
                    -scheme SBJson5_iOS
                    -destination "platform=iOS Simulator,name=iPhone 15 Pro"
                    | xcpretty

    test-macos:
        executor: default
        steps:
            - checkout
            - run:
                name: Run tests
                command: >
                    xcodebuild test
                    -scheme SBJson5_macOS
                    -destination "platform=macOS,arch=arm64"
                    | xcpretty

    pod-lib-lint:
        executor: default
        steps:
            - checkout
            - run: sed "s/%VERSION%/$CIRCLE_BUILD_NUM/" RELEASING/SBJson.template.podspec > SBJson.podspec
            - run: pod lib lint

    carthage-build:
        executor: default
        steps:
            - checkout
            - run: carthage build --use-xcframeworks --no-skip-current
